/* Generated by Yosys 0.65+59 (git sha1 94ec78b6e, g++ 13.3.0-6ubuntu2~24.04.1 -fPIC -O3) */

module counter(clk, rst, count);
  input clk;
  wire clk;
  input rst;
  wire rst;
  output [3:0] count;
  wire [3:0] count;
  wire _00_;
  wire _01_;
  wire _02_;
  wire _03_;
  wire _04_;
  wire _05_;
  wire _06_;
  wire _07_;
  wire _08_;
  wire _09_;
  wire [3:0] _10_;
  INV_X1 _11_ (
    .A(count[0]),
    .ZN(_10_[0])
  );
  INV_X1 _12_ (
    .A(rst),
    .ZN(_04_)
  );
  NAND2_X1 _13_ (
    .A1(count[1]),
    .A2(count[0]),
    .ZN(_08_)
  );
  NAND3_X1 _14_ (
    .A1(count[2]),
    .A2(count[1]),
    .A3(count[0]),
    .ZN(_09_)
  );
  XNOR2_X1 _15_ (
    .A(count[3]),
    .B(_09_),
    .ZN(_10_[3])
  );
  XNOR2_X1 _16_ (
    .A(count[2]),
    .B(_08_),
    .ZN(_10_[2])
  );
  XOR2_X1 _17_ (
    .A(count[1]),
    .B(count[0]),
    .Z(_10_[1])
  );
  INV_X1 _18_ (
    .A(rst),
    .ZN(_05_)
  );
  INV_X1 _19_ (
    .A(rst),
    .ZN(_06_)
  );
  INV_X1 _20_ (
    .A(rst),
    .ZN(_07_)
  );
  DFFR_X1 _21_ (
    .CK(clk),
    .D(_10_[0]),
    .Q(count[0]),
    .QN(_01_),
    .RN(_06_)
  );
  DFFR_X1 _22_ (
    .CK(clk),
    .D(_10_[1]),
    .Q(count[1]),
    .QN(_02_),
    .RN(_05_)
  );
  DFFR_X1 _23_ (
    .CK(clk),
    .D(_10_[2]),
    .Q(count[2]),
    .QN(_03_),
    .RN(_04_)
  );
  DFFR_X1 _24_ (
    .CK(clk),
    .D(_10_[3]),
    .Q(count[3]),
    .QN(_00_),
    .RN(_07_)
  );
endmodule
